### PR TITLE
Update dependencies & modernize development workflow

### PR DESCRIPTION
**Pull request by tmilewski**
@gm0t I went to update the dependencies and wound up in a rabbit-hole of vastly outdated Webpack configurations. This PR modernizes that flow.

Let me know if you find any issues.

I'll likely make more updates later, but I didn't want to conflate the two workstreams.

Thanks!

### CODE REVIEW

**Comment by tmilewski** [comment]
@gm0t Any thoughts?

**Comment by hlolli** [comment]
Looks nice, maybe you could publish your fork to npm meanwhile?

**Comment by gm0t** [comment]
Hey @tmilewski , thanks a lot for your great job, it looks awesome!
I'm very sorry that it took me so long to merge it :(

**Comment by tmilewski** [comment]
@gm0t Thanks, and no problem! Any chance of pushing to `npm`?

**Pull request merged**
