### PR TITLE
[feat]: add callback props `onFixedToggle`

### PR DESCRIPTION
**Pull request by GitScrum**

### CODE REVIEW

**Comment by GitScrum** [comment]
@gm0t Hi, if you not have time merge and publish please get me access and I will do it

**Comment by gm0t** [comment]
@GitScrum Hi! Thanks for your pull-request. 
**hasFixed** - sounds strange, I think it would be better to call it **onFixedToggle**, this way it is easier to understand the purpose of this field. What do you think?

**Comment by GitScrum** [comment]
@gm0t Thank you, it did not occur to me at once, I will change

**Comment by GitScrum** [comment]
@gm0t ready. Please let me know when you publish

**Comment by GitScrum** [comment]
@gm0t Thanks!

**Pull request merged**
